server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**
          filters:
            - name: CircuitBreaker
              args:
                name: restaurant-service
                fallbackuri: forward:/restaurantServiceFallBackMethod
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/restaurant/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderServiceFallBackMethod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
 
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



